switched from sysV init to systemd init style

diff --git a/src/usr/local/bin/busmaster b/src/usr/local/bin/busmaster
--- a/src/usr/local/bin/busmaster
+++ b/src/usr/local/bin/busmaster
@@ -1,20 +1,20 @@
 #!/bin/sh
 
-while getopts ":p:" opt; do
-        case ${opt} in
-        p )
-                PIDFILE=$OPTARG
-#                echo $$ > ${PIDFILE}
-        ;;
-        \? )
-                echo "Invalid option: $OPTARG" 1>&2
-        ;;
-        : )
-                echo "Invalid option: $OPTARG requires an argument" 1>&2
-        ;;
-        esac
-done
-shift $((OPTIND -1))
+#while getopts ":p:" opt; do
+#        case ${opt} in
+#        p )
+#                PIDFILE=$OPTARG
+##                echo $$ > ${PIDFILE}
+#        ;;
+#        \? )
+#                echo "Invalid option: $OPTARG" 1>&2
+#        ;;
+#        : )
+#                echo "Invalid option: $OPTARG requires an argument" 1>&2
+#        ;;
+#        esac
+#done
+#shift $((OPTIND -1))
 
 
 # **************************************************************
@@ -42,13 +42,13 @@ shift $((OPTIND -1))
 # *     -p : port number to listen to for cgi-bin requests     *
 # *                                                            *
 # **************************************************************
-/usr/local/bin/DS401_Master -i0x66 -x /etc/gcdc/busmaster-config.xml -d &
-SPID=$!
-#echo ${SPID}
-if [ -n "$PIDFILE" ];
-then
-       echo ${SPID} > ${PIDFILE}
-fi
+/usr/local/bin/DS401_Master -i0x66 -x /etc/gcdc/busmaster-config.xml -d
+#SPID=$!
+##echo ${SPID}
+#if [ -n "$PIDFILE" ];
+#then
+#       echo ${SPID} > ${PIDFILE}
+#fi
 
 #DS401_Master -i0x33 -x config.xml -d  -d 
 #DS401_Master -i0x41 -x config.xml -d -d
diff --git a/src/usr/local/bin/can-socat-setup b/src/usr/local/bin/can-socat-setup
--- a/src/usr/local/bin/can-socat-setup
+++ b/src/usr/local/bin/can-socat-setup
@@ -10,28 +10,28 @@ else
 fi
 
 
-while getopts ":p:" opt; do
-	case ${opt} in
-	p )
-		PIDFILE=$OPTARG
-#		echo $$ > ${PIDFILE}
-	;;
-	\? )
-		echo "Invalid option: $OPTARG" 1>&2
-	;;
-	: )
-		echo "Invalid option: $OPTARG requires an argument" 1>&2
-	;;
-	esac
-done
-shift $((OPTIND -1))
+#while getopts ":p:" opt; do
+#	case ${opt} in
+#	p )
+#		PIDFILE=$OPTARG
+##		echo $$ > ${PIDFILE}
+#	;;
+#	\? )
+#		echo "Invalid option: $OPTARG" 1>&2
+#	;;
+#	: )
+#		echo "Invalid option: $OPTARG requires an argument" 1>&2
+#	;;
+#	esac
+#done
+#shift $((OPTIND -1))
 
 #sudo socat -d -d INTERFACE:can0,pf=29,type=3,prototype=1 TCP-LISTEN:2000,fork,reuseaddr
 #sudo socat INTERFACE:can0,pf=29,type=3,prototype=1 TCP-LISTEN:2000,fork,reuseaddr
-socat INTERFACE:can0,pf=29,type=3,prototype=1 UDP-LISTEN:2000,fork,reuseaddr,sndbuf=32 &
-SPID=$!
-#echo ${SPID}
-if [ -n "$PIDFILE" ];
-then
-	echo ${SPID} > ${PIDFILE}
-fi
+socat INTERFACE:can0,pf=29,type=3,prototype=1 UDP-LISTEN:2000,fork,reuseaddr,sndbuf=32 
+#SPID=$!
+##echo ${SPID}
+#if [ -n "$PIDFILE" ];
+#then
+#	echo ${SPID} > ${PIDFILE}
+#fi
diff --git a/src/usr/local/bin/data-logger b/src/usr/local/bin/data-logger
--- a/src/usr/local/bin/data-logger
+++ b/src/usr/local/bin/data-logger
@@ -5,29 +5,29 @@ if [ "$JAVA_HOME" = "" ]; then
 	JAVA_HOME=/usr/lib/jvm/jdk-8-oracle-arm32-vfp-hflt/jre
 fi
 
-while getopts ":p:" opt; do
-        case ${opt} in
-        p )
-                PIDFILE=$OPTARG
-#                echo $$ > ${PIDFILE}
-        ;;
-        \? )
-                echo "Invalid option: $OPTARG" 1>&2
-        ;;
-        : )
-                echo "Invalid option: $OPTARG requires an argument" 1>&2
-        ;;
-        esac
-done
-shift $((OPTIND -1))
+#while getopts ":p:" opt; do
+#        case ${opt} in
+#        p )
+#                PIDFILE=$OPTARG
+##                echo $$ > ${PIDFILE}
+#        ;;
+#        \? )
+#                echo "Invalid option: $OPTARG" 1>&2
+#        ;;
+#        : )
+#                echo "Invalid option: $OPTARG requires an argument" 1>&2
+#        ;;
+#        esac
+#done
+#shift $((OPTIND -1))
 
 #Makes sure to use the correct jre
-$JAVA_HOME/bin/java -jar /usr/local/share/java/jco-dl-1v1.jar --xml-config "/etc/gcdc/loggerconfig.xml" --address 'localhost' -dir /var/www/html/data &
-SPID=$!
-echo ${SPID}
-if [ -n "$PIDFILE" ];
-then
-       echo ${SPID} > ${PIDFILE}
-fi
+$JAVA_HOME/bin/java -jar /usr/local/share/java/jco-dl-1v1.jar --xml-config "/etc/gcdc/loggerconfig.xml" --address 'localhost' -dir /var/www/html/data
+#SPID=$!
+#echo ${SPID}
+#if [ -n "$PIDFILE" ];
+#then
+#       echo ${SPID} > ${PIDFILE}
+#fi
 
 
